#!/bin/bash

# GitHub Actions Setup Guide for UnoReverse CI/CD Pipeline
# This script provides instructions for configuring GitHub Actions

echo "======================================"
echo "📋 GitHub Actions Setup Instructions"
echo "======================================"
echo ""

echo "STEP 1: Add Slack Webhook Secret"
echo "=================================="
echo ""
echo "1. Go to your GitHub repository"
echo "2. Navigate to: Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo "4. Name: SLACK_WEBHOOK_URL"
echo "5. Value: <your-slack-webhook-url>"
echo "   (Get this from: https://api.slack.com/apps → Your App → Incoming Webhooks)"
echo "6. Click 'Add secret'"
echo ""

echo "STEP 2: Enable GitHub Container Registry (GHCR)"
echo "==============================================="
echo ""
echo "1. Go to Settings → Developer settings → Personal access tokens → Tokens (classic)"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select scopes:"
echo "   - repo (full control)"
echo "   - write:packages"
echo "   - read:packages"
echo "4. Copy the token"
echo "5. Go back to repository Settings → Secrets and variables → Actions"
echo "6. Click 'New repository secret'"
echo "7. Name: GHCR_PAT"
echo "8. Value: <your-personal-access-token>"
echo ""

echo "STEP 3: Configure Repository Permissions"
echo "========================================"
echo ""
echo "1. Go to Settings → Actions → General"
echo "2. Under 'Workflow permissions', select:"
echo "   ✓ Read and write permissions"
echo "   ✓ Allow GitHub Actions to create and approve pull requests"
echo "3. Click 'Save'"
echo ""

echo "STEP 4: Verify Workflow Trigger Settings"
echo "========================================"
echo ""
echo "1. Go to Settings → Actions → General"
echo "2. Under 'Actions permissions', select:"
echo "   ✓ Allow all actions and reusable workflows"
echo "3. Click 'Save'"
echo ""

echo "STEP 5: Test the Pipeline"
echo "========================="
echo ""
echo "Option A: Via Push"
echo "  git add ."
echo "  git commit -m 'Test GitHub Actions'"
echo "  git push origin develop"
echo ""
echo "Option B: Manual Trigger (if enabled)"
echo "  1. Go to Actions tab"
echo "  2. Select 'UnoReverse CI/CD Pipeline'"
echo "  3. Click 'Run workflow'"
echo "  4. Select branch and click 'Run workflow'"
echo ""

echo "STEP 6: Monitor Pipeline Execution"
echo "=================================="
echo ""
echo "1. Go to Actions tab in your repository"
echo "2. Click on the latest workflow run"
echo "3. View logs for each job"
echo "4. Check Slack for notifications (if configured)"
echo ""

echo "======================================"
echo "🔧 Environment Variables Reference"
echo "======================================"
echo ""
echo "REGISTRY: ghcr.io"
echo "IMAGE_NAME: \${{ github.repository }}"
echo "BACKEND_PORT: 8083"
echo "FRONTEND_PORT: 9030"
echo ""

echo "======================================"
echo "📊 Pipeline Branches"
echo "======================================"
echo ""
echo "develop branch:"
echo "  ✓ Runs full pipeline"
echo "  ✓ Deploys to staging"
echo "  ✓ Sends Slack notifications"
echo ""
echo "main branch:"
echo "  ✓ Runs full pipeline"
echo "  ✓ Builds and pushes images to GHCR"
echo "  ✓ Deploys to production"
echo "  ✓ Sends Slack notifications"
echo ""

echo "pull_request:"
echo "  ✓ Runs build, lint, security, and database validation"
echo "  ✗ Does NOT deploy or push images"
echo ""

echo "======================================"
echo "🚨 Troubleshooting"
echo "======================================"
echo ""
echo "Issue: Workflow fails with 'Error: Resource not accessible by integration'"
echo "Solution: Check Repository permissions under Settings → Actions → General"
echo ""
echo "Issue: 'SLACK_WEBHOOK_URL secret not found'"
echo "Solution: Add the secret in Settings → Secrets and variables → Actions"
echo ""
echo "Issue: 'Permission denied' when pushing to GHCR"
echo "Solution: Create PAT with write:packages scope and add as GHCR_PAT secret"
echo ""
echo "Issue: Slack notifications not sending"
echo "Solution:"
echo "  1. Verify SLACK_WEBHOOK_URL is set correctly"
echo "  2. Check Slack app permissions in your workspace"
echo "  3. Test webhook manually: curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"test\"}' YOUR_WEBHOOK_URL"
echo ""

echo "======================================"
echo "✅ Verification Checklist"
echo "======================================"
echo ""
echo "□ SLACK_WEBHOOK_URL secret added"
echo "□ Repository permissions enabled"
echo "□ Actions enabled in repository"
echo "□ .github/workflows/ci-cd.yml committed"
echo "□ Slack workspace has incoming webhook"
echo "□ Test push to develop branch"
echo "□ Verify Slack notification received"
echo ""

echo "======================================"
echo "📝 Useful Links"
echo "======================================"
echo ""
echo "GitHub Actions Docs: https://docs.github.com/en/actions"
echo "Slack API Apps: https://api.slack.com/apps"
echo "GHCR Documentation: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry"
echo "GitHub Secrets: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions"
echo ""
